repos:
  - repo: https://github.com/prettier/prettier
    rev: "master" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: master
    hooks:
      - id: shfmt
